version: "2"
services:
  app:
    container_name: application
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "27018:27018"
    environment:
      - PORT=27018
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo