mutation RESURECT_HERO {
  resetHero{
    id
    level
    balance
    damage
    level_up
    companions{
      companion{
        name
      }
      level
    }
  }
}

mutation HERO_LEVEL_UP {
  level_up{
    id
    level
    balance
    damage
    level_up
    resurection_points
    resurection_bonus
    critical_chance
    critical_damage
    all_damage
    companion_damage
    hero_damage
    boss_gold
    upgrade_cost
    luck
    companions{
      companion{
        id
        name
        dps
        image
        cost
      }
      level
    }
    artefacts{
      artefact{
        id
        name
        image
        multilpier
        stat
        rarity
        cost
      }
      level
    }
    gearpieces{
      id
      image
      multilpier
      type
      rarity
      name
      equipped
    }
    zone{
      monster{
        health
        image
        type
        drop_chance
        gold
      }
      award
      drop_chance
      level
    }
    owner{
      id
      username
      email
    }
  }
}

mutation CREATE_HERO {
	createHero{
    id
    level
    balance
    damage
    level_up
    resurection_points
    resurection_bonus
    critical_chance
    critical_damage
    all_damage
    companion_damage
    hero_damage
    boss_gold
    upgrade_cost
    luck
    companions{
      companion{
        id
        name
        dps
        image
        cost
      }
      level
    }
    artefacts{
      artefact{
        id
        name
        image
        multilpier
        stat
        rarity
        cost
      }
      level
    }
    gearpieces{
      id
      image
      multilpier
      type
      rarity
      name
      equipped
    }
    zone{
      monster{
        health
        image
        type
        drop_chance
        gold
      }
      award
      drop_chance
      level
    }
    owner{
      id
      username
      email
    }
  }
}

query GET_HERO {
  getHero{
    id
    level
    balance
    damage
    level_up
    resurection_points
    resurection_bonus
    critical_chance
    critical_damage
    all_damage
    companion_damage
    hero_damage
    boss_gold
    upgrade_cost
    luck
    companions{
      companion{
        id
        name
        dps
        image
        cost
      }
      level
    }
    artefacts{
      artefact{
        id
        name
        image
        multilpier
        stat
        rarity
        cost
      }
      level
    }
    gearpieces{
      id
      image
      multilpier
      type
      rarity
      name
      equipped
    }
    zone{
      monster{
        health
        image
        type
        drop_chance
        gold
      }
      award
      drop_chance
      level
    }
    owner{
      id
      username
      email
    }
  }
}

